// ─────────────────────────────────────────
// B) 포켓몬 데이터
// 1~2세대(1~251) 중 대표 샘플 10마리 + 구조 설명
// 실제 서비스: 251마리 전체 데이터로 확장 필요
// ─────────────────────────────────────────
import type { PokemonData } from "./types";

export const POKEMON_DATA: PokemonData[] = [
  {
    id: 1,
    name: "이상해씨",
    nameEn: "Bulbasaur",
    types: ["grass", "poison"],
    colorAffinity: {
      main: ["green", "teal", "olive"],
      sub: ["purple", "blue", "navy"],
    },
    moodAffinity: ["calm", "normal"],
    styleTags: ["minimal", "casual", "amekaji"],
    rarity: 1,
    description: "오늘도 천천히, 꾸준하게 자라는 하루를 보내자!",
  },
  {
    id: 4,
    name: "파이리",
    nameEn: "Charmander",
    types: ["fire"],
    colorAffinity: {
      main: ["red", "orange", "flame"],
      sub: ["yellow", "cream", "gold"],
    },
    moodAffinity: ["excited", "normal"],
    styleTags: ["street", "sporty", "dandy"],
    rarity: 1,
    description: "내 꼬리의 불꽃처럼 오늘 하루도 활활 타올라봐!",
  },
  {
    id: 7,
    name: "꼬부기",
    nameEn: "Squirtle",
    types: ["water"],
    colorAffinity: {
      main: ["blue", "navy", "sky"],
      sub: ["teal", "white", "aqua"],
    },
    moodAffinity: ["calm", "sad", "normal"],
    styleTags: ["casual", "sporty", "minimal"],
    rarity: 1,
    description: "파도처럼 흘러가다 보면 괜찮아질 거야.",
  },
  {
    id: 25,
    name: "피카츄",
    nameEn: "Pikachu",
    types: ["electric"],
    colorAffinity: {
      main: ["yellow", "gold", "lemon"],
      sub: ["red", "brown", "orange"],
    },
    moodAffinity: ["excited", "normal", "annoyed"],
    styleTags: ["casual", "street", "sporty", "girly"],
    rarity: 2,
    description: "피카! 오늘 하루도 전기 충전 완료!",
  },
  {
    id: 39,
    name: "푸린",
    nameEn: "Jigglypuff",
    types: ["normal"],
    colorAffinity: {
      main: ["pink", "rose", "blush"],
      sub: ["white", "lavender", "peach"],
    },
    moodAffinity: ["calm", "sad", "normal"],
    styleTags: ["girly", "casual", "vintage"],
    rarity: 1,
    description: "노래를 불러줄게. 잠깐 쉬어도 괜찮아.",
  },
  {
    id: 54,
    name: "고라파덕",
    nameEn: "Psyduck",
    types: ["water", "psychic"],
    colorAffinity: {
      main: ["yellow", "cream", "lemon"],
      sub: ["blue", "teal", "white"],
    },
    moodAffinity: ["annoyed", "sad", "normal"],
    styleTags: ["casual", "minimal", "street"],
    rarity: 1,
    description: "머리가 아파도 괜찮아. 오늘만큼은 내가 곁에 있을게.",
  },
  {
    id: 94,
    name: "팬텀",
    nameEn: "Gengar",
    types: ["ghost", "poison"],
    colorAffinity: {
      main: ["purple", "violet", "dark"],
      sub: ["black", "navy", "indigo"],
    },
    moodAffinity: ["annoyed", "sad", "excited"],
    styleTags: ["techwear", "street", "vintage"],
    rarity: 2,
    description: "어둠 속에서도 웃을 수 있어. 나처럼!",
  },
  {
    id: 133,
    name: "이브이",
    nameEn: "Eevee",
    types: ["normal"],
    colorAffinity: {
      main: ["beige", "cream", "brown"],
      sub: ["white", "peach", "gold"],
    },
    moodAffinity: ["calm", "normal", "excited"],
    styleTags: ["casual", "girly", "dandy", "amekaji", "vintage"],
    rarity: 2,
    description: "어떤 모습으로도 변할 수 있어. 오늘의 나도 특별해!",
  },
  {
    id: 143,
    name: "잠만보",
    nameEn: "Snorlax",
    types: ["normal"],
    colorAffinity: {
      main: ["blue", "navy", "slate"],
      sub: ["beige", "cream", "white"],
    },
    moodAffinity: ["calm", "sad"],
    styleTags: ["casual", "minimal"],
    rarity: 2,
    description: "쉬는 것도 실력이야. 오늘 하루 충분히 쉬어봐.",
  },
  {
    id: 249,
    name: "루gia",
    nameEn: "Lugia",
    types: ["psychic", "flying"],
    colorAffinity: {
      main: ["white", "silver", "pearl"],
      sub: ["blue", "sky", "teal"],
    },
    moodAffinity: ["calm", "normal"],
    styleTags: ["formal", "minimal", "dandy"],
    rarity: 3,
    description: "바다 위를 나는 것처럼, 오늘도 자유롭게.",
  },
  // ── 추가 샘플 (15마리) ──
  {
    id: 6,
    name: "리자몽",
    nameEn: "Charizard",
    types: ["fire", "flying"],
    colorAffinity: {
      main: ["orange", "red", "flame"],
      sub: ["teal", "blue", "gold"],
    },
    moodAffinity: ["excited", "annoyed"],
    styleTags: ["street", "techwear", "dandy"],
    rarity: 2,
    description: "진짜 강함은 폭발할 때 알 수 있어!",
  },
  {
    id: 52,
    name: "나옹",
    nameEn: "Meowth",
    types: ["normal"],
    colorAffinity: {
      main: ["cream", "beige", "gold"],
      sub: ["brown", "white", "yellow"],
    },
    moodAffinity: ["normal", "excited", "annoyed"],
    styleTags: ["street", "casual", "dandy"],
    rarity: 1,
    description: "동전이 반짝반짝~ 오늘 운수 대통!",
  },
  {
    id: 63,
    name: "캐이시",
    nameEn: "Abra",
    types: ["psychic"],
    colorAffinity: {
      main: ["gold", "yellow", "amber"],
      sub: ["brown", "cream", "purple"],
    },
    moodAffinity: ["calm", "sad"],
    styleTags: ["minimal", "formal", "techwear"],
    rarity: 1,
    description: "텔레파시로 느꼈어. 오늘 너의 하루 잘 될 거야.",
  },
  {
    id: 79,
    name: "야돈",
    nameEn: "Slowpoke",
    types: ["water", "psychic"],
    colorAffinity: {
      main: ["pink", "salmon", "peach"],
      sub: ["white", "cream", "light-blue"],
    },
    moodAffinity: ["calm", "sad", "normal"],
    styleTags: ["casual", "minimal", "amekaji"],
    rarity: 1,
    description: "느려도 괜찮아. 천천히가도 결국 도착해.",
  },
  {
    id: 113,
    name: "럭키",
    nameEn: "Chansey",
    types: ["normal"],
    colorAffinity: {
      main: ["pink", "rose", "blush"],
      sub: ["white", "cream", "lavender"],
    },
    moodAffinity: ["calm", "excited", "normal"],
    styleTags: ["girly", "casual", "formal"],
    rarity: 2,
    description: "행운의 알을 나눠줄게! 오늘 하루도 건강하게~",
  },
  {
    id: 116,
    name: "쏘드라",
    nameEn: "Horsea",
    types: ["water"],
    colorAffinity: {
      main: ["blue", "teal", "aqua"],
      sub: ["white", "sky", "navy"],
    },
    moodAffinity: ["calm", "normal"],
    styleTags: ["minimal", "casual", "sporty"],
    rarity: 1,
    description: "잉크를 뿜어 흔적을 남겨봐. 오늘 하루도 기억에 남도록!",
  },
  {
    id: 131,
    name: "라프라스",
    nameEn: "Lapras",
    types: ["water", "ice"],
    colorAffinity: {
      main: ["teal", "cyan", "aqua"],
      sub: ["white", "ice", "blue"],
    },
    moodAffinity: ["calm", "sad", "normal"],
    styleTags: ["minimal", "casual", "formal"],
    rarity: 2,
    description: "넓은 바다를 건너는 것처럼, 오늘도 앞으로 나아가자.",
  },
  {
    id: 152,
    name: "치코리타",
    nameEn: "Chikorita",
    types: ["grass"],
    colorAffinity: {
      main: ["green", "lime", "sage"],
      sub: ["white", "yellow", "cream"],
    },
    moodAffinity: ["calm", "normal", "excited"],
    styleTags: ["girly", "casual", "minimal", "amekaji"],
    rarity: 1,
    description: "새 시작은 언제나 상쾌해! 오늘도 파이팅!",
  },
  {
    id: 155,
    name: "브케인",
    nameEn: "Cyndaquil",
    types: ["fire"],
    colorAffinity: {
      main: ["red", "orange", "crimson"],
      sub: ["yellow", "cream", "blue"],
    },
    moodAffinity: ["excited", "normal"],
    styleTags: ["sporty", "casual", "street"],
    rarity: 1,
    description: "등불이 활활~ 꺼지지 않는 불꽃으로!",
  },
  {
    id: 158,
    name: "리아코",
    nameEn: "Totodile",
    types: ["water"],
    colorAffinity: {
      main: ["blue", "teal", "cerulean"],
      sub: ["yellow", "gold", "red"],
    },
    moodAffinity: ["excited", "annoyed", "normal"],
    styleTags: ["sporty", "street", "casual"],
    rarity: 1,
    description: "날카로운 이빨처럼 오늘 하루도 맹렬하게!",
  },
  {
    id: 175,
    name: "토게피",
    nameEn: "Togepi",
    types: ["normal"],
    colorAffinity: {
      main: ["white", "cream", "pearl"],
      sub: ["yellow", "pink", "red"],
    },
    moodAffinity: ["calm", "excited", "normal"],
    styleTags: ["girly", "casual", "minimal"],
    rarity: 2,
    description: "행복을 나눠줄게! 오늘도 사랑 가득한 하루~",
  },
  {
    id: 197,
    name: "블래키",
    nameEn: "Umbreon",
    types: ["dark"],
    colorAffinity: {
      main: ["black", "dark", "charcoal"],
      sub: ["yellow", "gold", "amber"],
    },
    moodAffinity: ["calm", "annoyed", "sad"],
    styleTags: ["techwear", "dandy", "street", "vintage"],
    rarity: 2,
    description: "밤이 깊을수록 별이 빛나는 법. 오늘도 그렇게.",
  },
  {
    id: 196,
    name: "에스피온",
    nameEn: "Espeon",
    types: ["psychic"],
    colorAffinity: {
      main: ["purple", "violet", "lavender"],
      sub: ["pink", "rose", "white"],
    },
    moodAffinity: ["calm", "normal"],
    styleTags: ["minimal", "formal", "girly"],
    rarity: 2,
    description: "미래를 보는 눈으로, 오늘의 최선을 택할게.",
  },
  {
    id: 245,
    name: "스이쿤",
    nameEn: "Suicune",
    types: ["water"],
    colorAffinity: {
      main: ["blue", "cyan", "crystal"],
      sub: ["white", "purple", "silver"],
    },
    moodAffinity: ["calm", "normal"],
    styleTags: ["formal", "minimal", "dandy"],
    rarity: 3,
    description: "바람을 타고 달려가자. 맑고 자유롭게.",
  },
];

// ── ID로 검색 ──
export function getPokemonById(id: number): PokemonData | undefined {
  return POKEMON_DATA.find((p) => p.id === id);
}

// ── 전체 ID 목록 ──
export const ALL_POKEMON_IDS = POKEMON_DATA.map((p) => p.id);
